[package]
name = "tashibot"
version = "0.1.0"
authors = ["Koki Takahashi <hakatasiloving@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.0.7"
serde = "1.0.92"
serde_derive = "1.0.92"

[[bin]]
name = "dijkstra"
path = "dijkstra.rs"